### ISSUE TITLE
`findElement` produces inconsistent results

### ISSUE THREAD

**Issue by mseijas** [thebrowsercompany/swift-webdriver#119]
I'm finding that `findElement` produces inconsistent results in finding the same element after a user interaction has occurred.

Repro steps:
1. Find button element
2. Click on button element
3. Sleep for a second
4. Find same button element in step 1

🔴 Step 4 fails and the element is not able to be found.

**Comment by Squidonomics** [comment]
There's a built in `retryTimeout` for the `findElement` function. You can override it by passing in your own timer.

**Comment by tristanlabelle** [comment]
Closing as not actionable without a repro.
