### ISSUE TITLE
Windows Application Driver receiving lots of requests while no UI interactions occur

### ISSUE THREAD

**Issue by mseijas** [thebrowsercompany/swift-webdriver#120]
I am finding that during an interval where no UI interactions are occurring the Windows Application Driver logs show that it's receiving a very high number of requests during this time. Additionally all these requests seem to be replied to with a 404 response.

Repro steps:
1. Find any element
2. Sleep for a second
3. Notice how the Windows Application Driver keeps getting A LOT requests that respond with 404 during this time

**Comment by tristanlabelle** [comment]
This is likely a result of the implicit wait emulation which was the default before https://github.com/thebrowsercompany/swift-webdriver/pull/153 . Please reopen if that is still an issue.
