### ISSUE TITLE
Thoughts on standardizing contributions and expanding docs

### ISSUE THREAD

**Issue by Squidonomics** [thebrowsercompany/swift-webdriver#126]
Would it be possible to standardize the contribution guidelines. Things like branch naming conventions, commit names. Essentially just making a `CONTRIBUTIONS.md` and some kind of use documentation for the use of the implemented methods. I have a few ideas but I wanted to see what peoples thoughts were on opening a pr for that.

**Comment by compnerd** [comment]
I think that adding a `CONTRIBUTIONS.md` is a great idea.  Would you be okay with doing an initial skeleton and we can help fill in the gaps?  It doesn't have to be perfect, we could evolve it over time.

**Comment by Squidonomics** [comment]
Sounds good, I'll open a pr for it later tonight.
