### ISSUE TITLE
Bug and fix - Requests : SessionTouchScroll

### ISSUE THREAD

**Issue by JohnECoro** [thebrowsercompany/swift-webdriver#128]
Typo in struct SessionTouchScroll - `CodableKeys` should be `CodingKeys`

**Comment by Squidonomics** [comment]
That's a great catch you're right according to the docs [here](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types) `CodingKeys` is the right name. Thank you for your contribution!
